# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(464, 459)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget_2 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.tab_4)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.structure_tree = QtGui.QTreeWidget(self.tab)
        self.structure_tree.setColumnCount(2)
        self.structure_tree.setObjectName(_fromUtf8("structure_tree"))
        self.structure_tree.headerItem().setText(0, _fromUtf8("1"))
        self.structure_tree.headerItem().setText(1, _fromUtf8("2"))
        self.gridLayout.addWidget(self.structure_tree, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.structure_tree_2 = QtGui.QTreeWidget(self.tab_3)
        self.structure_tree_2.setColumnCount(2)
        self.structure_tree_2.setObjectName(_fromUtf8("structure_tree_2"))
        self.structure_tree_2.headerItem().setText(0, _fromUtf8("1"))
        self.structure_tree_2.headerItem().setText(1, _fromUtf8("2"))
        self.gridLayout_2.addWidget(self.structure_tree_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.structure_tree_3 = QtGui.QTreeWidget(self.tab_2)
        self.structure_tree_3.setColumnCount(2)
        self.structure_tree_3.setObjectName(_fromUtf8("structure_tree_3"))
        self.structure_tree_3.headerItem().setText(0, _fromUtf8("1"))
        self.structure_tree_3.headerItem().setText(1, _fromUtf8("2"))
        self.gridLayout_3.addWidget(self.structure_tree_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.port_edit = QtGui.QLineEdit(self.groupBox_5)
        self.port_edit.setObjectName(_fromUtf8("port_edit"))
        self.gridLayout_5.addWidget(self.port_edit, 6, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 2)
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 5, 0, 1, 2)
        self.host_edit = QtGui.QLineEdit(self.groupBox_5)
        self.host_edit.setObjectName(_fromUtf8("host_edit"))
        self.gridLayout_5.addWidget(self.host_edit, 6, 0, 1, 4)
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 0, 4, 1, 1)
        self.srid_edit = QtGui.QLineEdit(self.groupBox_5)
        self.srid_edit.setObjectName(_fromUtf8("srid_edit"))
        self.gridLayout_5.addWidget(self.srid_edit, 9, 0, 1, 3)
        self.user_edit = QtGui.QLineEdit(self.groupBox_5)
        self.user_edit.setObjectName(_fromUtf8("user_edit"))
        self.gridLayout_5.addWidget(self.user_edit, 1, 0, 1, 4)
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 5, 4, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 8, 0, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 9, 3, 1, 1)
        self.pass_edit = QtGui.QLineEdit(self.groupBox_5)
        self.pass_edit.setObjectName(_fromUtf8("pass_edit"))
        self.gridLayout_5.addWidget(self.pass_edit, 1, 4, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_5.addWidget(self.label_13, 3, 0, 1, 4)
        self.db_edit = QtGui.QLineEdit(self.groupBox_5)
        self.db_edit.setObjectName(_fromUtf8("db_edit"))
        self.gridLayout_5.addWidget(self.db_edit, 4, 0, 1, 4)
        spacerItem2 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem2, 7, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem3, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 464, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Schulen", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Medizinische Versorgung", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Nahversorgung", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Auswertung", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Datenbank", None))
        self.label_6.setText(_translate("MainWindow", "Username", None))
        self.label_7.setText(_translate("MainWindow", "Host", None))
        self.label_10.setText(_translate("MainWindow", "Passwort", None))
        self.label_11.setText(_translate("MainWindow", "Port", None))
        self.label_12.setText(_translate("MainWindow", "Projektion (SRID)", None))
        self.label_13.setText(_translate("MainWindow", "Datenbank", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Einstellungen", None))

